include:
  - component: $CI_SERVER_FQDN/ci-templates/docker-build/build-push@v0.0.5
    inputs:
      # Container registry configuration
      container_registry: docker.io
      container_registry_path: docker.io/nikosch86/${CI_PROJECT_NAME}
      container_registry_user: ${DOCKER_REGISTRY_USER}
      container_registry_password: ${DOCKER_REGISTRY_PASSWORD}
      # Job configuration
      tags:
        - docker
        - virtex
      docker_image: docker:28
      docker_dind_image: docker:28-dind
      build_directory: .
      default_branch: develop

stages:
  - build

  # rules:
  #   # Run on schedule (every 3 days at 22:20)
  #   - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "periodic_build"
  #   # Run on master branch pushes
  #   - if: $CI_COMMIT_BRANCH == "master"
  #   # Run on tag pushes
  #   - if: $CI_COMMIT_TAG
  #   # Run on merge requests
  #   - if: $CI_PIPELINE_SOURCE == "merge_request_event"
